### ISSUE TITLE
Invalid type 'Q' in unpack at analyze_hc_restore.pl line 204.

### ISSUE THREAD

**Issue by Iamnoone1** [philsmd/analyze_hc_restore#1]
Im new to perl and I don't know whats happening? Below is my restore file (Im not able to attach here) and why does it this display this error? My hashcat command line can be seen in that file when that 204 line is commented.

https://drive.google.com/open?id=0B_HUjZ6JvH_oX2s0Z0F0bE5zbmM

**Comment by philsmd** [comment]
Are you using a 32 bit operating system or a 32 bit perl interpreter?
According to the perl docs (http://perldoc.perl.org/functions/pack.html):
`Quads are available only if your system supports 64-bit integer values _and_ if Perl has been compiled to support those. Raises an exception otherwise.`

I would guess that any modern operating system and up to date version of perl supports this.
Can you try to fix (e.g update your perl version or OS) and confirm that?

**Comment by Iamnoone1** [comment]
Yes..thats the problem. Thanks a lot!
