### ISSUE TITLE
Possible to calculate password position from progress?

### ISSUE THREAD

**Issue by shoeper** [philsmd/analyze_hc_restore#6]
Hi, great tool. Is it possible to calculate the current password from the progress or restore point? At least it looked like when taking a position close to the progress it would continue (e.g. progress was a little bit more than 50% and I took the number of lines divided 2).

**Comment by philsmd** [comment]
You should always use the --skip value of hashcat to continue cracking and this value depends on the last **restore point** value. It is also adviceable (at least if you are not 100% sure) to give it a little bit of room, e.g. use 45% instead of 50% (but this depends on the keyspace value), just to be 100% sure that every password was tested.

So my suggestion is to use the hashcat tools at your disposal: i.e. use the command with the `--keyspace` option to calculate the total keyspace and use e.g. 0.45 * keyspace_value for your `--skip` run. I.e. you do not need to tamper with a .restore file, but just can use the command line switches that are also used for distributed cracking (`--skip`, `--keyspace`, maybe even `--limit`).

Hope this helps.
